// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWBPcN2W-cFF7L6CSRT2tmjCae579_tCo',
    appId: '1:772356996224:web:6659062be0f119ed97fa65',
    messagingSenderId: '772356996224',
    projectId: 'taskmanager-ng0604',
    authDomain: 'taskmanager-ng0604.firebaseapp.com',
    storageBucket: 'taskmanager-ng0604.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3q0qQT9sX2TjvNfdIWxB_s3A-_GM-S4',
    appId: '1:772356996224:android:2ee44e55ec90010a97fa65',
    messagingSenderId: '772356996224',
    projectId: 'taskmanager-ng0604',
    storageBucket: 'taskmanager-ng0604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfGrq8WHz-71MPJNwIH7-KPcxSgz3PDLY',
    appId: '1:772356996224:ios:3c14b8c419b217c797fa65',
    messagingSenderId: '772356996224',
    projectId: 'taskmanager-ng0604',
    storageBucket: 'taskmanager-ng0604.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfGrq8WHz-71MPJNwIH7-KPcxSgz3PDLY',
    appId: '1:772356996224:ios:3c14b8c419b217c797fa65',
    messagingSenderId: '772356996224',
    projectId: 'taskmanager-ng0604',
    storageBucket: 'taskmanager-ng0604.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWBPcN2W-cFF7L6CSRT2tmjCae579_tCo',
    appId: '1:772356996224:web:ba4c3a7cb98f233997fa65',
    messagingSenderId: '772356996224',
    projectId: 'taskmanager-ng0604',
    authDomain: 'taskmanager-ng0604.firebaseapp.com',
    storageBucket: 'taskmanager-ng0604.firebasestorage.app',
  );

}